name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'LICENSE'
      - 'NOTICE'
      - 'PROJECT'
      - 'SECURITY_CONTACTS'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'LICENSE'
      - 'NOTICE'
      - 'PROJECT'
      - 'SECURITY_CONTACTS'

jobs:
  build-agent:
      runs-on: ubuntu-20.04
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.10

      - name: build agent
        run: make host-agent-binaries

  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Check Docker Version
      run: docker --version

    - name: Uninstall podman if installed
      run: sudo apt-get purge podman && sudo rm -f /etc/cni/net.d/cni.lock && sudo rm -rf /etc/cni/net.d/87-podman.conflist
      
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: turn off swap
      run: sudo swapoff -a
    
    - name: Set netfilter conntrack max
      run: sudo sysctl -w net.netfilter.nf_conntrack_max=131072

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.10

    - name: Install ginkgo
      run: go install github.com/onsi/ginkgo/v2/ginkgo@v2.9.2

    - name: Install prequisit packages
      run: sudo apt update && sudo apt install -qq --yes socat ebtables ethtool conntrack

    - name: Run test make target
      run: make test

    - name: Upload test coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: cover.out
        verbose: true
